<?php

namespace JCV\UploadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrackPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackPointRepository extends EntityRepository
{
}
