services:
    form.type.datePicker:
        class: JCV\UploadBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: datePicker }
    form.type.dateTimePicker:
            class: JCV\UploadBundle\Form\Type\DateTimePickerType
            tags:
                - { name: form.type, alias: dateTimePicker }




