JCV\UploadBundle\Entity\Upload:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: originalFile
    properties:
        uploadFile:
            - File:
                maxSize: 1024k